package interfaz;

import javax.swing.JOptionPane;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import dao.ProductoDAO;
import java.util.Date;
import javax.swing.event.DocumentEvent;
import modelo.Producto;
import modelo.Vendedor;

/**
 *
 * @author Cassandra
 */
public class frameAlmacen extends javax.swing.JInternalFrame
{
    
    private Vendedor vendedorAct;

    /**
     * Creates new form frameClientes
     */
    public frameAlmacen(Vendedor v)
    {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);

        txtClave.getDocument().addDocumentListener(new javax.swing.event.DocumentListener()
        {
            @Override
            public void insertUpdate(DocumentEvent e)
            {
                filtrarProductos();
            }

            @Override
            public void removeUpdate(DocumentEvent e)
            {
                filtrarProductos();
            }

            @Override
            public void changedUpdate(DocumentEvent e)
            {
                filtrarProductos();
            }                        
        });
        
        this.vendedorAct = v;
        habilitarAcciones();
    }
    
    public void habilitarAcciones()
    {
        if (vendedorAct.getPuesto() == 1)
        {
            tabbedPane.setEnabledAt(1, true);
            eliminarPro.setEnabled(true);
        } else
        {
            tabbedPane.setEnabledAt(1, false);
            eliminarPro.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        tabbedPane = new javax.swing.JTabbedPane();
        panelConsulta = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        eliminarPro = new javax.swing.JButton();
        txtClave = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAlmacen = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        panelRegistros = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        registroPro = new javax.swing.JButton();
        txtPrecio = new javax.swing.JTextField();
        txtClaveReg = new javax.swing.JTextField();
        txtRegistro = new javax.swing.JTextField();
        txtPrecauciones = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtCant_almacen = new javax.swing.JTextField();
        txtEfectos = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtAdministracion = new javax.swing.JTextField();
        dateVencimiento = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        txtDescuento = new javax.swing.JTextField();
        modificarPro = new javax.swing.JButton();
        limpiarPPro = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setBorder(null);
        setTitle("Almacen");
        setPreferredSize(new java.awt.Dimension(700, 550));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener()
        {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt)
            {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelConsulta.setMinimumSize(new java.awt.Dimension(680, 530));
        panelConsulta.setPreferredSize(new java.awt.Dimension(680, 530));
        panelConsulta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel6.setText("Nombre:");
        panelConsulta.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        eliminarPro.setBackground(new java.awt.Color(204, 0, 0));
        eliminarPro.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        eliminarPro.setText("Eliminar");
        eliminarPro.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                eliminarProActionPerformed(evt);
            }
        });
        panelConsulta.add(eliminarPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, -1, -1));

        txtClave.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        txtClave.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtClaveActionPerformed(evt);
            }
        });
        panelConsulta.add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 370, 28));

        tableAlmacen.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        tableAlmacen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String []
            {
                "Clave", "Nombre", "Fecha de vencimiento", "Vía de administración", "No. Registro sanitario", "Efectos Secundarios", "Advertencias", "Stock", "Precio", "Descuento"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableAlmacen);

        panelConsulta.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 660, 320));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo.png"))); // NOI18N
        panelConsulta.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 530));

        tabbedPane.addTab("Consulta de productos", panelConsulta);

        panelRegistros.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel1.setText("Clave:");
        panelRegistros.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel2.setText("Precauciones y advertencias:");
        panelRegistros.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, -1, 20));

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel3.setText("Precio:");
        panelRegistros.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel4.setText("Fecha de vencimiento:");
        panelRegistros.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, -1, 20));

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel5.setText("Vía de administración:");
        panelRegistros.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        registroPro.setBackground(new java.awt.Color(51, 255, 51));
        registroPro.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        registroPro.setText("Registrar");
        registroPro.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                registroProActionPerformed(evt);
            }
        });
        panelRegistros.add(registroPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 120, -1));

        txtPrecio.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        txtPrecio.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtPrecioActionPerformed(evt);
            }
        });
        panelRegistros.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 230, 40));

        txtClaveReg.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        txtClaveReg.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtClaveRegActionPerformed(evt);
            }
        });
        panelRegistros.add(txtClaveReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 230, 40));

        txtRegistro.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        txtRegistro.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtRegistroActionPerformed(evt);
            }
        });
        panelRegistros.add(txtRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 230, 40));

        txtPrecauciones.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        txtPrecauciones.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtPrecaucionesActionPerformed(evt);
            }
        });
        panelRegistros.add(txtPrecauciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 230, 40));

        jLabel13.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel13.setText("Cantidad almaccenada:");
        panelRegistros.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, -1, -1));

        txtCant_almacen.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        txtCant_almacen.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtCant_almacenActionPerformed(evt);
            }
        });
        panelRegistros.add(txtCant_almacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 230, 40));

        txtEfectos.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        txtEfectos.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtEfectosActionPerformed(evt);
            }
        });
        panelRegistros.add(txtEfectos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 230, 40));

        jLabel7.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel7.setText("Nombre:");
        panelRegistros.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        jLabel12.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel12.setText("Efectos secundarios:");
        panelRegistros.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        txtNombre.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtNombreActionPerformed(evt);
            }
        });
        panelRegistros.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 230, 40));

        jLabel14.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel14.setText("Número de registro sanitario:");
        panelRegistros.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, 20));

        txtAdministracion.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        txtAdministracion.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtAdministracionActionPerformed(evt);
            }
        });
        panelRegistros.add(txtAdministracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 230, 40));
        panelRegistros.add(dateVencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 230, 40));

        jLabel10.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel10.setText("Descuento:");
        panelRegistros.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, -1, -1));

        txtDescuento.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        txtDescuento.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtDescuentoActionPerformed(evt);
            }
        });
        panelRegistros.add(txtDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 230, 40));

        modificarPro.setBackground(new java.awt.Color(51, 255, 51));
        modificarPro.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        modificarPro.setText("Modificar");
        modificarPro.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                modificarProActionPerformed(evt);
            }
        });
        panelRegistros.add(modificarPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 120, -1));

        limpiarPPro.setBackground(new java.awt.Color(255, 0, 0));
        limpiarPPro.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        limpiarPPro.setText("Limpiar");
        limpiarPPro.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                limpiarPProActionPerformed(evt);
            }
        });
        panelRegistros.add(limpiarPPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 110, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo.png"))); // NOI18N
        panelRegistros.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 530));

        tabbedPane.addTab("Registro y modificación de productos", panelRegistros);

        getContentPane().add(tabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 0, 710, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtPrecioActionPerformed
    {//GEN-HEADEREND:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtClaveRegActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtClaveRegActionPerformed
    {//GEN-HEADEREND:event_txtClaveRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClaveRegActionPerformed

    private void txtPrecaucionesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtPrecaucionesActionPerformed
    {//GEN-HEADEREND:event_txtPrecaucionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecaucionesActionPerformed

    private void txtRegistroActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtRegistroActionPerformed
    {//GEN-HEADEREND:event_txtRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegistroActionPerformed

    private void txtEfectosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtEfectosActionPerformed
    {//GEN-HEADEREND:event_txtEfectosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEfectosActionPerformed

    private void registroProActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_registroProActionPerformed
    {//GEN-HEADEREND:event_registroProActionPerformed

        String clave = txtClaveReg.getText();
        String nombre = txtNombre.getText();
        String cant_alm = txtCant_almacen.getText();
        String precioStr = txtPrecio.getText();
        String administracion = txtAdministracion.getText();
        String registro = txtRegistro.getText();
        String efectos = txtEfectos.getText();
        String precauciones = txtPrecauciones.getText();
        String descuento = txtDescuento.getText();

        // Validaciones con expresiones regulares (puedes ajustarlas si alguna no es adecuada)
        String expClave = "[0-9]{1,20}";
        String expNombre = "[a-zA-Z\\s]{3,50}";
        String expPrecio = "[0-9]+(\\.[0-9]{1,2})?";
        String expAdministracion = "[a-zA-Z\\s]*";
        String expRegistro = "[0-9]{1,6}";
        String expEfectos = ".{5,100}";
        String expPrecauciones = ".{5,100}";

        Date fechaUtil = dateVencimiento.getDate();
        if (fechaUtil == null)
        {
            JOptionPane.showMessageDialog(frameAlmacen.this, "Por favor, selecciona una fecha válida.", "Fecha requerida", JOptionPane.WARNING_MESSAGE);
            return;
        }

        boolean valido = clave.matches(expClave)
                && nombre.matches(expNombre)
                && precioStr.matches(expPrecio)
                && administracion.matches(expAdministracion)
                && registro.matches(expRegistro)
                && efectos.matches(expEfectos)
                && precauciones.matches(expPrecauciones);

        if (!valido)
        {
            JOptionPane.showMessageDialog(frameAlmacen.this, "Hay campos vacíos o con formato incorrecto.", "Error de validación", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try
        {
            int claveInt = Integer.parseInt(clave);
            double precio = Double.parseDouble(precioStr);
            int cant_alma = Integer.parseInt(cant_alm);
            int desc = Integer.parseInt(descuento);
            java.sql.Date fecha = new java.sql.Date(fechaUtil.getTime());
            
            Producto producto = new Producto();
            producto.setClave(claveInt);
            producto.setNombre(nombre);
            producto.setFecha_vencimiento(fecha);
            producto.setVia_admin(administracion);
            producto.setReg_sanitario(registro);
            producto.setEfectos_sec(efectos);
            producto.setAdvertencia(precauciones);
            producto.setCant_almacen(cant_alma);
            producto.setPrecio(precio);
            producto.setDescuento(desc);

            boolean exito = ProductoDAO.insertarProducto(producto);
            if (exito)
            {
                JOptionPane.showMessageDialog(frameAlmacen.this, "Producto registrado con éxito.", "Registro exitoso", JOptionPane.INFORMATION_MESSAGE);
                limpiarForm();
                llenarTablaAlmacen();
            } else
            {
                JOptionPane.showMessageDialog(frameAlmacen.this, "No se pudo registrar el producto.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex)
        {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(frameAlmacen.this, "Error al procesar los datos del producto.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_registroProActionPerformed

    private void eliminarProActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_eliminarProActionPerformed
    {//GEN-HEADEREND:event_eliminarProActionPerformed
        int filaSeleccionada = tableAlmacen.getSelectedRow();
        
        if (filaSeleccionada == -1)
        {
            JOptionPane.showMessageDialog(this, "Selecciona un producto a eliminar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int confirmacion = JOptionPane.showConfirmDialog(this, "¿Estás seguro de eliminar este producto?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
        if (confirmacion != JOptionPane.YES_OPTION)
        {
            return;
        }
        
        int idProducto = Integer.parseInt(tableAlmacen.getValueAt(filaSeleccionada, 0).toString());
        
        ProductoDAO productoDAO = new ProductoDAO();
        productoDAO.eliminarProducto(idProducto);
        llenarTablaAlmacen();
    }//GEN-LAST:event_eliminarProActionPerformed

    private void txtClaveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtClaveActionPerformed
    {//GEN-HEADEREND:event_txtClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClaveActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtNombreActionPerformed
    {//GEN-HEADEREND:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtAdministracionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtAdministracionActionPerformed
    {//GEN-HEADEREND:event_txtAdministracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdministracionActionPerformed

    private void limpiarPProActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_limpiarPProActionPerformed
    {//GEN-HEADEREND:event_limpiarPProActionPerformed
        limpiarForm();
    }//GEN-LAST:event_limpiarPProActionPerformed

    private void modificarProActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_modificarProActionPerformed
    {//GEN-HEADEREND:event_modificarProActionPerformed
        String claveSt = txtClaveReg.getText().trim();
        String cant_almSt = txtCant_almacen.getText().trim();
        String descuentoSt = txtDescuento.getText().trim();
        String precioSt = txtPrecio.getText().trim();
        
        if (claveSt.isEmpty() || cant_almSt.isEmpty() || descuentoSt.isEmpty() || precioSt.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Por favor llena los datos correspondientes", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return ;
        }
        
        Date fechaUtil = dateVencimiento.getDate();
        
        if (fechaUtil == null)
        {
            JOptionPane.showMessageDialog(frameAlmacen.this, "Por favor, selecciona una fecha válida.", "Fecha requerida", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int confirmacion = JOptionPane.showConfirmDialog(this,
                "¿Estás seguro de modificar este producto?", "Confirmar",
                JOptionPane.YES_NO_OPTION);
        if (confirmacion != JOptionPane.YES_OPTION)
        {
            return;
        }
        
        int claveInt = Integer.parseInt(claveSt);
        int cant_almInt = Integer.parseInt(cant_almSt);
        int descuentoInt = Integer.parseInt(descuentoSt);
        double precioDo = Double.parseDouble(precioSt);
        java.sql.Date fecha = new java.sql.Date(fechaUtil.getTime());
        
        Producto producto = new Producto();
        
        producto.setClave(claveInt);
        producto.setCant_almacen(cant_almInt);
        producto.setDescuento(descuentoInt);
        producto.setPrecio(precioDo);
        producto.setFecha_vencimiento(fecha);
        
        ProductoDAO productoDAO = new ProductoDAO();
        if (productoDAO.actualizarProducto(producto))
        {
            JOptionPane.showMessageDialog(this, "Producto actualizado correctamente.");
            limpiarForm(); 
            llenarTablaAlmacen();
        } else
        {
            JOptionPane.showMessageDialog(this, "Error al actualizar el producto.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_modificarProActionPerformed

    private void txtDescuentoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtDescuentoActionPerformed
    {//GEN-HEADEREND:event_txtDescuentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescuentoActionPerformed

    private void txtCant_almacenActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtCant_almacenActionPerformed
    {//GEN-HEADEREND:event_txtCant_almacenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCant_almacenActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameOpened
    {//GEN-HEADEREND:event_formInternalFrameOpened
        llenarTablaAlmacen();
    }//GEN-LAST:event_formInternalFrameOpened

    public void limpiarForm()
    {
        txtAdministracion.setText("");
        txtCant_almacen.setText("");
        txtClaveReg.setText("");
        txtDescuento.setText("");
        txtEfectos.setText("");
        txtNombre.setText("");
        txtPrecauciones.setText("");
        txtPrecio.setText("");
        txtRegistro.setText("");
        dateVencimiento.setDate(null);
    }
    
    public void filtrarProductos()
    {
        String textoBusqueda = txtClave.getText().trim().toLowerCase();
        DefaultTableModel modeloTabla = (DefaultTableModel) tableAlmacen.getModel();

        modeloTabla.setRowCount(0);

        ProductoDAO productoDAO = new ProductoDAO();

        List<Producto> productos = productoDAO.obtenerProducto();

        for (Producto producto : productos)
        {
            if (producto.getNombre().toLowerCase().contains(textoBusqueda))
            {
                Object[] fila =
                {
                    producto.getClave(),
                    producto.getNombre(),
                    producto.getFecha_vencimiento(),
                    producto.getVia_admin(),
                    producto.getReg_sanitario(),
                    producto.getEfectos_sec(),
                    producto.getAdvertencia(),
                    producto.getCant_almacen(),
                    producto.getPrecio(),
                    producto.getDescuento(),
                };
                modeloTabla.addRow(fila);
            }
        }
    }

    private void llenarTablaAlmacen()
    {
        DefaultTableModel modelo = (DefaultTableModel) tableAlmacen.getModel();
        modelo.setRowCount(0);

        List<Producto> productos = ProductoDAO.listarProducto();

        for (Producto producto : productos)
        {
            Object[] fila =
            {
                producto.getClave(),
                producto.getNombre(),
                producto.getFecha_vencimiento(),
                producto.getVia_admin(),
                producto.getReg_sanitario(),
                producto.getEfectos_sec(),
                producto.getAdvertencia(),
                producto.getCant_almacen(),
                producto.getPrecio(),
                producto.getDescuento(),
            };
            modelo.addRow(fila);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dateVencimiento;
    private javax.swing.JButton eliminarPro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpiarPPro;
    private javax.swing.JButton modificarPro;
    private javax.swing.JPanel panelConsulta;
    private javax.swing.JPanel panelRegistros;
    private javax.swing.JButton registroPro;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTable tableAlmacen;
    private javax.swing.JTextField txtAdministracion;
    private javax.swing.JTextField txtCant_almacen;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtClaveReg;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtEfectos;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecauciones;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtRegistro;
    // End of variables declaration//GEN-END:variables
}
