package interfaz;

import java.awt.Image;
import java.awt.Toolkit;
import modelo.Vendedor;

/**
 *
 * @author Cassandra
 */
public class vtnPrincipal extends javax.swing.JFrame
{

    private Vendedor vendedorAct;

    public vtnPrincipal()
    {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Principal");
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/medico.png"));
        setIconImage(icon);
    }

    /**
     * Creates new form vtnProductos
     */
    public vtnPrincipal(Vendedor vendedor)
    {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Principal");
        this.vendedorAct = vendedor;
        nameEmp.setText(vendedor.getNombre());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        btnVentas = new javax.swing.JButton();
        btnCliente = new javax.swing.JButton();
        btnAlmacen = new javax.swing.JButton();
        btnAdmi = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        desktopPaneControl = new javax.swing.JDesktopPane();
        nameEmp = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });

        jPanel1.setPreferredSize(new java.awt.Dimension(930, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/de-venta.png"))); // NOI18N
        btnVentas.setToolTipText("Ventas.");
        btnVentas.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnVentasActionPerformed(evt);
            }
        });
        jPanel1.add(btnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        btnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/servicio-al-cliente.png"))); // NOI18N
        btnCliente.setToolTipText("Clientes.");
        btnCliente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnClienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        btnAlmacen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gestion-de-materiales.png"))); // NOI18N
        btnAlmacen.setToolTipText("Almacen.");
        btnAlmacen.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAlmacenActionPerformed(evt);
            }
        });
        jPanel1.add(btnAlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        btnAdmi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/contratacion.png"))); // NOI18N
        btnAdmi.setToolTipText("Registrar empleados.");
        btnAdmi.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAdmiActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdmi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, -1, -1));

        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/beneficio-financiero.png"))); // NOI18N
        btnReportes.setToolTipText("Reporte de ventas.");
        btnReportes.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnReportesActionPerformed(evt);
            }
        });
        jPanel1.add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        javax.swing.GroupLayout desktopPaneControlLayout = new javax.swing.GroupLayout(desktopPaneControl);
        desktopPaneControl.setLayout(desktopPaneControlLayout);
        desktopPaneControlLayout.setHorizontalGroup(
            desktopPaneControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        desktopPaneControlLayout.setVerticalGroup(
            desktopPaneControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        jPanel1.add(desktopPaneControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 700, 550));

        nameEmp.setBackground(new java.awt.Color(0, 0, 0));
        nameEmp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nameEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario22.png"))); // NOI18N
        jPanel1.add(nameEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        btnCerrar.setBackground(new java.awt.Color(153, 0, 0));
        btnCerrar.setText("Cerrar Sesión");
        btnCerrar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(734, 10, 120, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlmacenActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAlmacenActionPerformed
    {//GEN-HEADEREND:event_btnAlmacenActionPerformed
        desktopPaneControl.removeAll();
        frameAlmacen fA = new frameAlmacen(vendedorAct);
        desktopPaneControl.add(fA).setVisible(true);
    }//GEN-LAST:event_btnAlmacenActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnReportesActionPerformed
    {//GEN-HEADEREND:event_btnReportesActionPerformed
        desktopPaneControl.removeAll();
        frameReportes fR = new frameReportes();        
        desktopPaneControl.repaint();
        desktopPaneControl.add(fR).setVisible(true);
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnVentasActionPerformed
    {//GEN-HEADEREND:event_btnVentasActionPerformed
        desktopPaneControl.removeAll();
        frameVentas fV = new frameVentas(vendedorAct);
        desktopPaneControl.add(fV).setVisible(true);
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnClienteActionPerformed
    {//GEN-HEADEREND:event_btnClienteActionPerformed
        desktopPaneControl.removeAll();
        frameClientes fC = new frameClientes(vendedorAct);
        desktopPaneControl.add(fC).setVisible(true);
    }//GEN-LAST:event_btnClienteActionPerformed

    private void btnAdmiActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAdmiActionPerformed
    {//GEN-HEADEREND:event_btnAdmiActionPerformed
        desktopPaneControl.removeAll();
        frameAdmin fA = new frameAdmin();
        desktopPaneControl.add(fA).setVisible(true);
    }//GEN-LAST:event_btnAdmiActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        if (vendedorAct.getPuesto() == 2)
        {
            btnAlmacen.setVisible(true);
            btnCliente.setVisible(true);
            btnVentas.setVisible(true);
            btnReportes.setVisible(false);
            btnAdmi.setVisible(false);
        } else
        {
            btnAlmacen.setVisible(true);
            btnCliente.setVisible(true);
            btnVentas.setVisible(true);
            btnReportes.setVisible(true);
            btnAdmi.setVisible(true);
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCerrarActionPerformed
    {//GEN-HEADEREND:event_btnCerrarActionPerformed
        vendedorAct = null;
        vtnIngreso ingreso = new vtnIngreso();
        ingreso.setVisible(true);
        dispose();      
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(vtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(vtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(vtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(vtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new vtnPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmi;
    private javax.swing.JButton btnAlmacen;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnVentas;
    private javax.swing.JDesktopPane desktopPaneControl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nameEmp;
    // End of variables declaration//GEN-END:variables
}
